<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>fea6ed41-7037-4517-b162-6fe187c7e70b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.Keycloak" Version="13.3.3-preview.1.26264.13" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.3.3" />
    <PackageReference Include="Aspire.Hosting.Yarp" Version="13.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProfileService\ProfileService.csproj" />
    <ProjectReference Include="..\QuestionService\QuestionService.csproj" />
    <ProjectReference Include="..\SearchService\SearchService.csproj" />
  </ItemGroup>

</Project>
